CREATE TABLE [dbo].[TextSpeech](
	[AUTO_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[AGE] [int] NOT NULL,
	[GENDER] [char](1) NOT NULL,
	[DATA_ID] [int] NOT NULL,
	[LANG_ID] [int] NOT NULL,
	[DOMAIN_ID] [int] NOT NULL,
	[OUTPUT_DATA] [varbinary](max) NOT NULL,
	[DATASET_ID] [int] NOT NULL,
	[ADDED_ON] [datetime] NULL,
 CONSTRAINT [PK_Text_Speech] PRIMARY KEY CLUSTERED 
(
	[AUTO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]