CREATE TABLE [dbo].[LANGUAGE_ID_MAPPING](
	[LANGUAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[VALUE] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NULL,
 CONSTRAINT [PK_LANGUAGE_ID_MAPPING] PRIMARY KEY CLUSTERED 
(
	[LANGUAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]