CREATE TABLE [dbo].[QUALIFICATION_ID_MAPPING](
	[QUALIFICATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[VALUE] [nchar](20) NOT NULL,
 CONSTRAINT [PK_QUALIFICATION_ID_MAPPING] PRIMARY KEY CLUSTERED 
(
	[QUALIFICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]