CREATE TABLE [dbo].[SUB_CATEGORIES](
	[SUBCATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_SUB_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[SUBCATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]