CREATE TABLE [dbo].[USER_INFO](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](250) NOT NULL,
	[GENDER] [char](1) NOT NULL,
	[AGE] [int] NOT NULL,
	[QUALIFICATION_ID] [int] NOT NULL,
	[LANG_ID_1] [int] NOT NULL,
	[LANG_ID_2] [int] NOT NULL,
	[LANG_ID_3] [int] NOT NULL,
 CONSTRAINT [PK_USER_INFO] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]