CREATE TABLE [dbo].[Images](
	[DATA_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IMAGE] [image] NULL,
	[SOURCE_ID] [int] NULL,
	[ADDED_ON] [datetime] NULL,
	[LANG_ID] [int] NULL,
	[DOMAIN_ID] [int] NULL,
	[DATASET_ID] [int] NULL,
 CONSTRAINT [PK_GENERAL_IMAGE] PRIMARY KEY CLUSTERED 
(
	[DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]