
USE [master]
GO

/****** Object:  Database [TextToSpeech]    Script Date: 16-07-2019 11:54:09 ******/
CREATE DATABASE [TextToSpeech] ON  PRIMARY 
( NAME = N'TextToSpeech', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\TextToSpeech\TextToSpeech.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TextToSpeech_log', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\TextToSpeech\TextToSpeech_log.ldf' , SIZE = 3136KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TextToSpeech] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TextToSpeech].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TextToSpeech] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [TextToSpeech] SET ANSI_NULLS OFF
GO

ALTER DATABASE [TextToSpeech] SET ANSI_PADDING OFF
GO

ALTER DATABASE [TextToSpeech] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [TextToSpeech] SET ARITHABORT OFF
GO

ALTER DATABASE [TextToSpeech] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [TextToSpeech] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [TextToSpeech] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [TextToSpeech] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [TextToSpeech] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [TextToSpeech] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [TextToSpeech] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [TextToSpeech] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [TextToSpeech] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [TextToSpeech] SET  DISABLE_BROKER
GO

ALTER DATABASE [TextToSpeech] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [TextToSpeech] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [TextToSpeech] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [TextToSpeech] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [TextToSpeech] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [TextToSpeech] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [TextToSpeech] SET RECOVERY SIMPLE
GO

ALTER DATABASE [TextToSpeech] SET  MULTI_USER
GO

ALTER DATABASE [TextToSpeech] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [TextToSpeech] SET DB_CHAINING OFF
GO

USE [TextToSpeech]
GO

/****** Object:  Table [dbo].[TextSpeech]    Script Date: 16-07-2019 11:54:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

USE [master]
GO

ALTER DATABASE [TextToSpeech] SET  READ_WRITE
GO
