
USE [master]
GO

/****** Object:  Database [ImageToText]    Script Date: 16-07-2019 11:53:23 ******/
CREATE DATABASE [ImageToText] ON  PRIMARY 
( NAME = N'ImageToText', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\ImageToText\ImageToText.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ImageToText_log', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\ImageToText\ImageToText_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ImageToText] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ImageToText].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ImageToText] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [ImageToText] SET ANSI_NULLS OFF
GO

ALTER DATABASE [ImageToText] SET ANSI_PADDING OFF
GO

ALTER DATABASE [ImageToText] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [ImageToText] SET ARITHABORT OFF
GO

ALTER DATABASE [ImageToText] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [ImageToText] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [ImageToText] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [ImageToText] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [ImageToText] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [ImageToText] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [ImageToText] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [ImageToText] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [ImageToText] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [ImageToText] SET  DISABLE_BROKER
GO

ALTER DATABASE [ImageToText] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [ImageToText] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [ImageToText] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [ImageToText] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [ImageToText] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [ImageToText] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [ImageToText] SET RECOVERY SIMPLE
GO

ALTER DATABASE [ImageToText] SET  MULTI_USER
GO

ALTER DATABASE [ImageToText] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [ImageToText] SET DB_CHAINING OFF
GO

USE [ImageToText]
GO

/****** Object:  Table [dbo].[ImageText]    Script Date: 16-07-2019 11:53:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [ImageToText] SET  READ_WRITE
GO
