
USE [master]
GO

/****** Object:  Database [CLRCP_MASTER]    Script Date: 16-07-2019 11:52:27 ******/
CREATE DATABASE [CLRCP_MASTER] ON  PRIMARY 
( NAME = N'CLRCP_MASTER', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\CLRCP_MASTER\CLRCP_MASTER.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CLRCP_MASTER_log', FILENAME = N'E:\CLRCP\Database\MSSQL_DATA\CLRCP_MASTER\CLRCP_MASTER_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CLRCP_MASTER] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLRCP_MASTER].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CLRCP_MASTER] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET ANSI_NULLS OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET ANSI_PADDING OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET ARITHABORT OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [CLRCP_MASTER] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [CLRCP_MASTER] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET  DISABLE_BROKER
GO

ALTER DATABASE [CLRCP_MASTER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [CLRCP_MASTER] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [CLRCP_MASTER] SET RECOVERY SIMPLE
GO

ALTER DATABASE [CLRCP_MASTER] SET  MULTI_USER
GO

ALTER DATABASE [CLRCP_MASTER] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [CLRCP_MASTER] SET DB_CHAINING OFF
GO

USE [CLRCP_MASTER]
GO

/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[DATASET_SUBCATEGORY_MAPPING]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[DATASETS]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[DOMAIN_ID_MAPPING]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[LANGUAGE_ID_MAPPING]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[LOGIN_DETAILS]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[QUALIFICATION_ID_MAPPING]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[SOURCE_ID_MAPPING]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[SUB_CATEGORIES]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[USER_INFO]    Script Date: 16-07-2019 11:52:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

USE [master]
GO

ALTER DATABASE [CLRCP_MASTER] SET  READ_WRITE
GO
